services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    networks:
      - template

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - template

  template:
    image: template:backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/test
    env_file:
      - .env
    ports:
      - 4000:4000
    networks:
      - template

networks:
  template:
    external: true
